import numpy as np

from pysersic.loss import student_t_loss_free_sys

from scalpel import Scalpel

# Set up config dictionary
config = {

    "cutout_kwargs" : {

        "F090W_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F090W_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f090w.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f090w",
        },

        "F115W_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F115W_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f115w.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f115w",
        },

        "F150W_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F150W_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f150w.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f150w",
        },

        "F182M_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F182M_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f182m.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f182m",
        },

        "F200W_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F200W_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f200w.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f200w",
        },

         "F210M_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F210M_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f210m.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f210m",
        },

        "F277W_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F277W_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f277w.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f277w",
        },

        # F335M has weird data
        # "F335M_kwargs" : {
        #     "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
        #     "data_name" : "gs9209_F335M_cutout.fits",
        #     "data_ext" : "SCI",
        #     "centre" : (334, 334),
        #     "width" : 30,
        #     "height" : 30,
        #     "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
        #     "psf_name" : "mpsf_f335m.fits",
        #     "psf_ext" : None,
        #     "snr_limit" : 10,
        #     "plot" : False,
        #     "filter" : "f335m",
        # },

        "F356W_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F356W_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f356w.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f356w",
        },

        "F410M_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F410M_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f410m.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f410m",
        },

        "F430M_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F430M_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f430m.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f430m",
        },

        "F444W_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F444W_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f444w.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f444w",
        },

        "F460M_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F460M_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f460m.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f460m",
        },

        "F480M_kwargs" : {
            "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cutouts",
            "data_name" : "gs9209_F480M_cutout.fits",
            "data_ext" : "SCI",
            "centre" : (334, 334),
            "width" : 30,
            "height" : 30,
            "psf_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/model_psfs",
            "psf_name" : "mpsf_f480m.fits",
            "psf_ext" : None,
            "snr_limit" : 10,
            "plot" : False,
            "filter" : "f480m",
        },
    },

    "cube_kwargs" : {
        "data_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/data_processed/gs-9209/cubes",
        "data_name" : "GS9209-4.67_jw3659_px0.05_dr_ODfde95.0_VSC_AMRC_mMSA_m2ff_xy96_CTX1236_v1.15.1_g235h-f170lp_cgs_s3d.fits",
        "data_ext" : "SCI",
        "wave_from_hdr" : True,
        "in_wave_units" : None,
        "out_wave_units" : None,
        "centre" : (44, 40),
        "width" : 20,
        "height" : 20,
        "wave_min" : None,
        "wave_max" : None,
    },

    "prior_dict" : {
        "uniform" : {
            # "r_eff" : (0.1, 5.0),
            "r_eff" : (0.1, 2.5),
            # "ellip" : (0.0, 1.0),
            "ellip" : (0.0, 0.5),
            # "n" : (2.0, 4.5),
            "n" : (1.0, 4.5),
        },
    },

    "fit_kwargs" : {
        "fit_type" : "simultaneous",
        "profile_type" : "sersic",
        "sky_type" : "none",
        "loss_func" : "student_t",
        "method" : "mcmc",
        "multifitter" : "bspline",
        "multifit_kwargs" : {
            "N_knots" : 5,
        },
        "use_cube_wave" : False,
        "invert_wave" : False,
        "seed" : 1000,
        "verbose" : True,
        "linked_params" : ["n", "ellip", "r_eff"],
        "const_params" : ["xc", "yc", "theta"],
        "out_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/outputs/gs-9209/scalpel_outputs/gs-9209_sersic",
        "fig_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/figures/gs-9209/scalpel_outputs/gs-9209_sersic",
    },

    # "fit_kwargs" : {
    #     "fit_type" : "simultaneous",
    #     "profile_type" : "sersic",
    #     "sky_type" : "none",
    #     "loss_func" : "student_t",
    #     "method" : "mcmc",
    #     "multifitter" : "poly",
    #     "multifit_kwargs" : {
    #         "poly_order" : 3,
    #     },
    #     "use_cube_wave" : False,
    #     "invert_wave" : False,
    #     "seed" : 1000,
    #     "verbose" : True,
    #     "linked_params" : ["n", "ellip", "r_eff"],
    #     "const_params" : ["xc", "yc", "theta"],
    #     "out_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/outputs/gs-9209/scalpel_outputs/gs-9209_sersic",
    #     "fig_dir" : "/Users/Jonah/PhD/Research/quiescent_galaxies/figures/gs-9209/scalpel_outputs/gs-9209_sersic",
    # },
}

# Create Scalpel object
scalpel = Scalpel(config)
scalpel.dissect()